In [4]:
tinggi = [51,72,64,87,90]
lebar = [100,201,51,12,10]
# cari area
print(type(tinggi))
tinggi * lebar

<class 'list'>


TypeError: can't multiply sequence by non-int of type 'list'

In [5]:
import numpy as np

In [8]:
arr_tinggi = np.array(tinggi)
arr_lebar = np.array(lebar)
# panjang = [10,20,30,40,50]
arr_panjang = np.array([10,20,30,40,50])

hasil = arr_tinggi * arr_lebar * arr_panjang * arr_tinggi
print(hasil, type(hasil))

[ 2601000 20839680  6266880  3633120  4050000] <class 'numpy.ndarray'>


# simpan posisi papan catur di dalam array -> 2D
[
    [1,2,3,4,5,6,7,8],
    [1,2,3,4,5,6,7,8],
    [1,2,3,4,5,6,7,8],
    [1,2,3,4,5,6,7,8],
    [1,2,3,4,5,6,7,8],
    [1,2,3,4,5,6,7,8],
    [1,2,3,4,5,6,7,8],
    [1,2,3,4,5,6,7,8],
]

In [9]:
# built-in function milik numpy, contohnya:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
np.ones(3)

array([1., 1., 1.])

In [12]:
np.empty(4)

array([1.16742670e-311, 9.34598926e-307, 1.33511562e-306, 6.23040373e-307])

In [13]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [14]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
for i in range(7,30,20): # range(start, stop, step)
    print(i)

7
27


In [38]:
arr_numbers = np.arange(7, 15, 20)
arr_numbers

array([7])

In [23]:
arr_numbers = np.append(arr_numbers, 15)
arr_numbers

array([ 7,  9, 11, 13, 15])

In [27]:
hasil = np.append(arr_numbers, [15, 17])
print(hasil)
print(type(hasil))

[ 7  9 11 13 15 15 17]
<class 'numpy.ndarray'>


In [29]:
tempel2list = np.append([1,2,3],[4,5,6])
print(type(tempel2list))

<class 'numpy.ndarray'>


In [36]:
hasil_return = np.delete(tempel2list, 1)
print(hasil_return)

[1 3 4 5 6]


In [41]:
random_nums = np.array([-1,1,-5,5,-30,30]) # ini sebuah array yang isinya tidak urut
np.sort(random_nums) # membuat array baru yang isinya urut

array([-30,  -5,  -1,   1,   5,  30])

In [42]:
random_nums # masih tidak berubah, tidak kena error by reference

array([ -1,   1,  -5,   5, -30,  30])

In [44]:
random_nums.ndim # bukan function, tidak perlu () invoke

1

In [55]:
arr_2d = np.array([
    ["o","x","o", " "],
    ["x","x","o", " "],
    ["o"," "," ", " "],
])

In [56]:
arr_2d.ndim

2

In [57]:
arr_2d.size

12

In [53]:
random_nums.size

6

In [58]:
arr_2d.shape

(3, 4)

In [64]:
random_nums.shape

(6,)

In [62]:
transposed = arr_2d.reshape(4,3)
transposed.shape
print(arr_2d)
print(transposed)

[['o' 'x' 'o' ' ']
 ['x' 'x' 'o' ' ']
 ['o' ' ' ' ' ' ']]
[['o' 'x' 'o']
 [' ' 'x' 'x']
 ['o' ' ' 'o']
 [' ' ' ' ' ']]


In [67]:
arr_nums_baru = random_nums[np.newaxis]
arr_nums_baru

array([[ -1,   1,  -5,   5, -30,  30]])

In [68]:
random_nums[np.newaxis, :]

array([[ -1,   1,  -5,   5, -30,  30]])

In [69]:
random_nums[:, np.newaxis]

array([[ -1],
       [  1],
       [ -5],
       [  5],
       [-30],
       [ 30]])

In [72]:
np.expand_dims(random_nums, axis=0)

array([[ -1,   1,  -5,   5, -30,  30]])

In [73]:
np.expand_dims(random_nums, axis=1)

array([[ -1],
       [  1],
       [ -5],
       [  5],
       [-30],
       [ 30]])

In [74]:
random_nums[-3:]

array([  5, -30,  30])

In [76]:
random_nums[1:4]

array([ 1, -5,  5])

cara indexing dan slicing di numpy array sama persis dengan di list

In [77]:
random_nums[random_nums < 0]

array([ -1,  -5, -30])

In [79]:
random_nums[random_nums % 2 == 1]

array([-1,  1, -5,  5])

In [80]:
random_nums[(random_nums < 0) & (random_nums % 2 == 1)]

array([-1, -5])

In [81]:
arr_a = np.array([[1, 2], [3,4]])
arr_a

array([[1, 2],
       [3, 4]])

In [82]:
arr_b = np.array([[5,6], [7,8]])
arr_b

array([[5, 6],
       [7, 8]])

In [84]:
np.vstack((arr_a, arr_b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [87]:
h_arr = np.hstack((arr_a, arr_b))
h_arr

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [92]:
hasil = np.hsplit(h_arr, 4) # kasih list yang isinya numpy array
print(hasil)
print(type(hasil))

[array([[1],
       [3]]), array([[2],
       [4]]), array([[5],
       [7]]), array([[6],
       [8]])]
<class 'list'>


In [96]:
np.hsplit(np.zeros(12), 3)

[array([0., 0., 0., 0.]), array([0., 0., 0., 0.]), array([0., 0., 0., 0.])]

In [97]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [102]:
b = a.view() # shallow copy, misalnya b di edit, a ikut ke edit
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [104]:
b[0] = 100
print(b)
print(a)

[100   1   2   3   4   5   6   7   8   9  10  11]
[100   1   2   3   4   5   6   7   8   9  10  11]


In [105]:
c = a.copy() # deep copy, misalnya c di edit, a tidak ikut ter edit
c[0] = 9
print(c)
print(a)

[ 9  1  2  3  4  5  6  7  8  9 10 11]
[100   1   2   3   4   5   6   7   8   9  10  11]


In [106]:
h_arr

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [107]:
h_arr.sum(axis=0)

array([ 4,  6, 12, 14])

In [108]:
h_arr.sum(axis=1)

array([14, 22])

In [110]:
h_arr + np.ones(8).reshape(2,4)

array([[2., 3., 6., 7.],
       [4., 5., 8., 9.]])

In [111]:
np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [112]:
np.ones(8).reshape(2,4)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [113]:
h_arr + np.ones(8).reshape(2,4)

array([[2., 3., 6., 7.],
       [4., 5., 8., 9.]])

In [114]:
h_arr - np.ones(8).reshape(2,4)

array([[0., 1., 4., 5.],
       [2., 3., 6., 7.]])

In [115]:
h_arr * (np.ones(8).reshape(2,4) + np.ones(8).reshape(2,4))

array([[ 2.,  4., 10., 12.],
       [ 6.,  8., 14., 16.]])

In [116]:
h_arr / (np.ones(8).reshape(2,4) + np.ones(8).reshape(2,4))

array([[0.5, 1. , 2.5, 3. ],
       [1.5, 2. , 3.5, 4. ]])

In [117]:
h_arr * 2

array([[ 2,  4, 10, 12],
       [ 6,  8, 14, 16]])

In [118]:
h_arr / 2

array([[0.5, 1. , 2.5, 3. ],
       [1.5, 2. , 3.5, 4. ]])

In [122]:
data_awal = h_arr + 3
data_awal

array([[ 4,  5,  8,  9],
       [ 6,  7, 10, 11]])

In [124]:
# min max sum mean std

data_awal.min()

4

In [125]:
data_awal.max()

11

In [126]:
data_awal.sum()

60

In [127]:
data_awal.mean()

7.5

In [128]:
data_awal.std()

2.29128784747792

[
    [1],
    [2,3],
    []
]

matrix, array 2D yang bentuknya pas
[
    [2,2,8],
    [3,3,3]
]

In [134]:
m1 = np.array([
    [1,2,3],
    [4,5,6]
])

m2 = np.array([
    [7,8],
    [9,10],
    [11,12]
])

hasil = np.dot(m1, m2) # melakukan dot product antara 2 matrix
hasil

array([[ 58,  64],
       [139, 154]])

dot product matrix tidak se simple angka 1 dikali angka 1, bisa baca lebih lanjut di sini https://www.mathsisfun.com/algebra/matrix-multiplying.html

In [135]:
hasil[0,0]

58

In [136]:
hasil[1]

array([139, 154])

In [138]:
hasil[1,1]

154

In [139]:
hasil[:,1]

array([ 64, 154])

In [140]:
hasil[-1]

array([139, 154])

In [141]:
m2

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [146]:
m2.reshape(2,3)

array([[ 7,  8,  9],
       [10, 11, 12]])

In [147]:
m2.T # row 1 jadi col 1, row 2 jadi col 2, seterusnya

array([[ 7,  9, 11],
       [ 8, 10, 12]])

In [148]:
np.zeros(3)

array([0., 0., 0.])

In [150]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [152]:
np.zeros((5,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [172]:
np.random.random((5,2,3))

array([[[0.01785951, 0.22314164, 0.85081693],
        [0.12699394, 0.94671724, 0.90935997]],

       [[0.51198727, 0.16553301, 0.38565729],
        [0.86916155, 0.95584785, 0.52995386]],

       [[0.64939154, 0.4993319 , 0.49109698],
        [0.95239832, 0.71090231, 0.15178726]],

       [[0.77479727, 0.53369329, 0.11451108],
        [0.67111889, 0.30321402, 0.53857214]],

       [[0.47253638, 0.58223886, 0.97686841],
        [0.91962491, 0.69784846, 0.22081172]]])

In [167]:
arr_3d = np.zeros((5,2,3))

In [168]:
arr_3d.flatten() # menjadi 1 dimensi

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [170]:
arr_3d.ravel() # sama seperti flatten tapi shallow copy, seperti view

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])